const productList01 = [
  {
    id: "pro01",
    name: "닭가슴살 스테이크 혼합[5종 2팩씩]",
    price: 18100,
    src: "./js/images/product01.jpg",
    hover: "./js/images/product01_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steak',
    popularity: 2
  },
  {
    id: "pro02",
    name: "닭가슴살 스테이크 오리지널",
    price: 17400,
    src: "./js/images/product02.jpg",
    hover: "./js/images/product02_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steak',
    popularity: 1
  },
  {
    id: "pro03",
    name: "닭가슴살 스테이크 고추맛",
    price: 18100,
    src: "./js/images/product03.jpg",
    hover: "./js/images/product03_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steak',
    popularity: 3
  },
  {
    id: "pro04",
    name: "닭가슴살 스테이크 야채맛",
    price: 18100,
    src: "./js/images/product04.jpg",
    hover: "./js/images/product04_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steak',
    popularity: 13

  },
  {
    id: "pro05",
    name: "닭가슴살 스테이크 갈릭맛",
    price: 18100,
    src: "./js/images/product05.jpg",
    hover: "./js/images/product05_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steak',
    popularity: '12'
  },
  {
    id: "pro06",
    name: "닭가슴살 스테이크 호박맛",
    price: 18100,
    src: "./js/images/product06.jpg",
    hover: "./js/images/product06_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steak',
    popularity: 23
  },
  {
    id: "pro07",
    name: "닭가슴살 볼 혼합",
    price: 20790,
    src: "./js/images/product07.jpg",
    hover: "./js/images/product07_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'ball',
    popularity: 11
  },
  {
    id: "pro08",
    name: "닭가슴살 볼 스파이시",
    price: 20790,
    src: "./js/images/product08.jpg",
    hover: "./js/images/product08_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'ball',
    popularity: 9
  },
  {
    id: "pro09",
    name: "닭가슴살 볼 오리지널",
    price: 20790,
    src: "./js/images/product09.jpg",
    hover: "./js/images/product09_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'ball',
    popularity: 10
  },
  {
    id: "pro10",
    name: "닭가슴살 볼 치즈",
    price: 20790,
    src: "./js/images/product10.jpg",
    hover: "./js/images/product10_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'ball',
    popularity: 8
  },
  {
    id: "pro11",
    name: "닭가슴살 볼 깻잎",
    price: 20790,
    src: "./js/images/product11.jpg",
    hover: "./js/images/product11_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'ball',
    popularity: 14
  },
  {
    id: "pro12",
    name: "닭가슴살 볼 자반김",
    price: 20790,
    src: "./js/images/product12.jpg",
    hover: "./js/images/product12_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'ball',
    popularity: 24
  },
  {
    id: "pro13",
    name: "소스 닭가슴살 스테이크 로스트 갈릭",
    price: 22900,
    src: "./js/images/product13.jpg",
    hover: "./js/images/product13_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'sauce',
    popularity: 7
  },
  {
    id: "pro14",
    name: "소스 닭가슴살 스테이크 매콤 토마토",
    price: 22900,
    src: "./js/images/product14.jpg",
    hover: "./js/images/product14_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'sauce',
    popularity: 6
  },
  {
    id: "pro15",
    name: "소스 닭가슴살 스테이크 토마토",
    price: 22900,
    src: "./js/images/product15.jpg",
    hover: "./js/images/product15_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'sauce',
    popularity: 5
  },
  {
    id: "pro16",
    name: "소스 닭가슴살 스테이크 자색고구마 까르보나라",
    price: 22900,
    src: "./js/images/product16.jpg",
    hover: "./js/images/product16_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'sauce',
    popularity: 22
    
  },
  {
    id: "pro17",
    name: "소스 닭가슴살 스테이크 흑마늘",
    price: 22900,
    src: "./js/images/product17.jpg",
    hover: "./js/images/product17_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'sauce',
    popularity: 21
  },
  {
    id: "pro18",
    name: "소스 닭가슴살 스테이크 혼합",
    price: 22900,
    src: "./js/images/product18.jpg",
    hover: "./js/images/product18_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'sauce',
    popularity: 4
  },
  {
    id: "pro19",
    name: "스팀 닭가슴살 마늘맛",
    price: 20600,
    src: "./js/images/product19.jpg",
    hover: "./js/images/product19_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steam',
    popularity: 15
  },
  {
    id: "pro20",
    name: "스팀 닭가슴살 고추맛",
    price: 20600,
    src: "./js/images/product20.jpg",
    hover: "./js/images/product20_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steam',
    popularity: 16
  },
  {
    id: "pro21",
    name: "스팀 닭가슴살 오리지널",
    price: 20600,
    src: "./js/images/product21.jpg",
    hover: "./js/images/product21_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steam',
    popularity: 18
  },
  {
    id: "pro22",
    name: "스팀 닭가슴살 혼합",
    price: 20600,
    src: "./js/images/product22.jpg",
    hover: "./js/images/product22_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steam',
    popularity: 17
  },
  {
    id: "pro23",
    name: "저염 스팀 닭가슴살 오리지널",
    price: 20600,
    src: "./js/images/product23.jpg",
    hover: "./js/images/product23_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'steam',
    popularity: 20
  },
  {
    id: "pro24",
    name: "프로틴 훈제 닭가슴살",
    price: 19300,
    src: "./js/images/product24.jpg",
    hover: "./js/images/product24_back.jpg",
    heart_off: "./js/images/heart_off.png",
    heart_on: "./js/images/heart_on.png",
    cart: "./js/images/cart.png",
    type: 'smoked',
    popularity: 19
  }
]

export default productList01
